name: Leopard Web Store CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests (Windows)
      working-directory: ./Leopard_Web_Store
      run: |
        python manage.py test
      env:
        SECRET_KEY: test-secret-key-123
        DEBUG: "True"

  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests (Linux)
      working-directory: ./Leopard_Web_Store
      run: |
        python manage.py test
      env:
        SECRET_KEY: test-secret-key-123
        DEBUG: "True"

  deploy-ssh:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    needs: [test-windows, test-ubuntu]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH and deploy
      run: |
        # Налаштовуємо SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Додаємо хост до known_hosts
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
        # Деплой через SSH
        echo "🚀 Початок деплою через SSH..."
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/dima/Projects/Leopard-Web-Store
          git pull origin main
          source .venv/bin/activate
          pip install -r requirements.txt
          cd Leopard_Web_Store
          python manage.py migrate
          python manage.py collectstatic --noinput
          pkill -f "python manage.py runserver" || true
          nohup python manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
          echo "✅ Деплой на сервер успішний!"
        EOF

    - name: Verify deployment
      run: |
        echo "🔍 Перевірка деплою..."
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          cd /home/dima/Projects/Leopard-Web-Store/Leopard_Web_Store
          echo '📊 Статус сервера:'
          ps aux | grep 'python manage.py runserver' | grep -v grep || echo '❌ Сервер не працює'
          echo '📋 Останні логи:'
          tail -5 server.log || echo 'Логи відсутні'
        "